import StyleDictionary from 'style-dictionary';

/**
 * Custom format: Tailwind v4 preset.
 *
 * Tailwind v4 is CSS-first — design tokens are declared inside an `@theme` block,
 * which both registers the CSS variables and generates matching utilities
 * (e.g. `--color-sample` → `bg-sample`, `text-sample`). Consumers import this file
 * from their app/global CSS to wire Canopy tokens into Tailwind.
 */
StyleDictionary.registerFormat({
  name: 'tailwind/preset-v4',
  format: ({ dictionary }) => {
    const lines = dictionary.allTokens.map(
      (token) => `  --${token.name}: ${token.$value ?? token.value};`,
    );
    return `/* Generated by Style Dictionary — Canopy Roots Tailwind v4 preset. Do not edit. */\n@theme {\n${lines.join('\n')}\n}\n`;
  },
});

/**
 * Custom format: typed TypeScript token export.
 *
 * Emits a `const` object plus a `Tokens` type so consumers get autocomplete and
 * type-safety when reading token values programmatically.
 */
StyleDictionary.registerFormat({
  name: 'typescript/typed-export',
  format: ({ dictionary }) => {
    const entries = dictionary.allTokens
      .map((token) => `  '${token.name}': '${token.$value ?? token.value}',`)
      .join('\n');
    return [
      '/* Generated by Style Dictionary — Canopy Roots typed token export. Do not edit. */',
      'export const tokens = {',
      entries,
      '} as const;',
      '',
      'export type Tokens = typeof tokens;',
      'export type TokenName = keyof Tokens;',
      '',
    ].join('\n');
  },
});

export default {
  source: ['tokens/**/*.json'],
  platforms: {
    css: {
      transformGroup: 'css',
      buildPath: 'dist/',
      files: [
        {
          destination: 'tokens.css',
          format: 'css/variables',
          options: { outputReferences: true },
        },
      ],
    },
    tailwind: {
      transformGroup: 'css',
      buildPath: 'dist/',
      files: [
        {
          destination: 'tailwind-preset.css',
          format: 'tailwind/preset-v4',
        },
      ],
    },
    ts: {
      transformGroup: 'css',
      buildPath: 'dist/',
      files: [
        {
          destination: 'tokens.ts',
          format: 'typescript/typed-export',
        },
      ],
    },
  },
};
