import StyleDictionary from 'style-dictionary';
import { getReferences, usesReferences } from 'style-dictionary/utils';

/**
 * Custom format: Tailwind v4 preset.
 *
 * Tailwind v4 is CSS-first — design tokens are declared inside an `@theme` block.
 * We use `@theme inline`, mapping each token name to a *reference* to its runtime
 * CSS variable (`--color-sample: var(--color-sample)`) rather than redeclaring the
 * value. This keeps `tokens.css` (`:root`) the single owner of the runtime vars
 * (no double declaration), and means a `.dark` remap in `tokens.css` cascades
 * straight through to the generated utilities (`bg-sample`, `text-sample`).
 * Consumers import this file from their app/global CSS to wire Canopy tokens into
 * Tailwind.
 */
StyleDictionary.registerFormat({
  name: 'tailwind/preset-v4',
  format: ({ dictionary }) => {
    const lines = dictionary.allTokens.map((token) => `  --${token.name}: var(--${token.name});`);
    return `/* Generated by Style Dictionary — Canopy Roots Tailwind v4 preset. Do not edit. */\n@theme inline {\n${lines.join('\n')}\n}\n`;
  },
});

/**
 * Custom format: typed TypeScript token export.
 *
 * Emits a `const` object plus a `Tokens` type so consumers get autocomplete and
 * type-safety when reading token values programmatically.
 *
 * Reference-aware: a token whose original `$value` references another token emits a
 * `var(--<ref-name>)` string (so the runtime CSS var — owned by `tokens.css` — is the
 * single source of the resolved value, and theming flows through). A non-referencing
 * primitive emits its literal value.
 *
 * Naming convention: the object key is the flattened, kebab-cased Style Dictionary
 * path (`color.sample` → `color-sample`), intentionally aligned with the CSS-var /
 * Tailwind `--color-*` namespace so a TS key, a CSS var, and a utility all share one
 * name. Spec 0003 formalizes the primitive-vs-semantic naming.
 */
StyleDictionary.registerFormat({
  name: 'typescript/typed-export',
  format: ({ dictionary }) => {
    const entries = dictionary.allTokens
      .map((token) => {
        const original = token.original.$value ?? token.original.value;
        let value = token.$value ?? token.value;
        if (usesReferences(original)) {
          // Replace each `{a.b}` reference in the original value with a reference to
          // the corresponding runtime CSS var (`var(--<transformed-kebab-name>)`).
          value = String(original);
          for (const ref of getReferences(original, dictionary.tokens)) {
            value = value.replace(`{${ref.path.join('.')}}`, `var(--${ref.name})`);
          }
        }
        return `  '${token.name}': '${value}',`;
      })
      .join('\n');
    return [
      '/* Generated by Style Dictionary — Canopy Roots typed token export. Do not edit. */',
      'export const tokens = {',
      entries,
      '} as const;',
      '',
      'export type Tokens = typeof tokens;',
      'export type TokenName = keyof Tokens;',
      '',
    ].join('\n');
  },
});

export default {
  source: ['tokens/**/*.json'],
  platforms: {
    css: {
      transformGroup: 'css',
      buildPath: 'dist/',
      files: [
        {
          destination: 'tokens.css',
          format: 'css/variables',
          options: { outputReferences: true },
        },
      ],
    },
    tailwind: {
      transformGroup: 'css',
      buildPath: 'dist/',
      files: [
        {
          destination: 'tailwind-preset.css',
          format: 'tailwind/preset-v4',
        },
      ],
    },
    ts: {
      transformGroup: 'css',
      buildPath: 'dist/',
      files: [
        {
          destination: 'tokens.ts',
          format: 'typescript/typed-export',
        },
      ],
    },
  },
};
