import StyleDictionary from 'style-dictionary';
import { getReferences, usesReferences } from 'style-dictionary/utils';

/**
 * Custom transform: drop a trailing `-default` segment from the kebab name.
 *
 * Used for the DEFAULT convention. A functional colour family (`success`,
 * `warning`, …) is BOTH a primitive ramp (`color.success.50…950`) and a single
 * semantic role. Style Dictionary cannot put a `$value` on the `color.success`
 * group node (it has children), so the semantic role lives at `color.success.DEFAULT`
 * — a sibling leaf. This transform renames `color-success-default` → `color-success`
 * so the role still emits `--color-success` (→ `bg-success`) while the ramp keeps
 * `--color-success-600` etc. (Mirrors Tailwind's own DEFAULT handling.)
 */
StyleDictionary.registerTransform({
  name: 'name/kebab-no-default',
  type: 'name',
  transform: (token) => token.name.replace(/-default$/, ''),
});

/**
 * The stock `css` transformGroup plus our `-default` strip appended after the
 * built-in `name/kebab` so the rename wins.
 */
const cssTransforms = [
  'attribute/cti',
  'name/kebab',
  'name/kebab-no-default',
  'time/seconds',
  'html/icon',
  'size/rem',
  'color/css',
  'asset/url',
  'fontFamily/css',
  'cubicBezier/css',
  'strokeStyle/css/shorthand',
  'border/css/shorthand',
  'transition/css/shorthand',
  'shadow/css/shorthand',
];

/**
 * Custom format: Tailwind v4 preset.
 *
 * Tailwind v4 is CSS-first — design tokens are declared inside an `@theme` block.
 * We use `@theme inline`, mapping each token name to a *reference* to its runtime
 * CSS variable (`--color-primary: var(--color-primary)`) rather than redeclaring the
 * value. This keeps `tokens.css` (`:root`) the single owner of the runtime vars
 * (no double declaration), and means a `.dark` remap in `tokens.css` cascades
 * straight through to the generated utilities (`bg-primary`, `text-primary`).
 * Consumers import this file from their app/global CSS to wire Canopy tokens into
 * Tailwind.
 */
StyleDictionary.registerFormat({
  name: 'tailwind/preset-v4',
  format: ({ dictionary }) => {
    const lines = dictionary.allTokens.map((token) => `  --${token.name}: var(--${token.name});`);
    // Spacing special-case: Tailwind v4 derives every p-*/m-*/gap-*/size-* utility
    // from a single `--spacing` base (utilities are computed as `calc(base * n)`),
    // NOT from individual `--space-*` vars. Emit the 4px base here so `p-4` = 1rem.
    // The `--space-*` vars still live in tokens.css for direct `var()` use.
    // This is a literal (not a `var()` self-reference) because it's a build-time
    // base Tailwind reads to generate utilities, with no runtime override.
    lines.unshift('  --spacing: 0.25rem;');
    return `/* Generated by Style Dictionary — Canopy Roots Tailwind v4 preset. Do not edit. */\n@theme inline {\n${lines.join('\n')}\n}\n`;
  },
});

/**
 * Custom format: typed TypeScript token export.
 *
 * Emits a `const` object plus a `Tokens` type so consumers get autocomplete and
 * type-safety when reading token values programmatically.
 *
 * Reference-aware: a token whose original `$value` references another token emits a
 * `var(--<ref-name>)` string (so the runtime CSS var — owned by `tokens.css` — is the
 * single source of the resolved value, and theming flows through). A non-referencing
 * primitive emits its literal value.
 *
 * Naming convention: the object key is the flattened, kebab-cased Style Dictionary
 * path (`color.moss.600` → `color-moss-600`; `color.primary` → `color-primary`),
 * intentionally aligned with the CSS-var / Tailwind `--color-*` namespace so a TS key,
 * a CSS var, and a utility all share one name. Primitives are ramp paths; semantics are
 * role paths that reference them.
 */
StyleDictionary.registerFormat({
  name: 'typescript/typed-export',
  format: ({ dictionary }) => {
    const entries = dictionary.allTokens
      .map((token) => {
        const original = token.original.$value ?? token.original.value;
        let value = token.$value ?? token.value;
        if (usesReferences(original)) {
          // Replace each `{a.b}` reference in the original value with a reference to
          // the corresponding runtime CSS var (`var(--<transformed-kebab-name>)`).
          value = String(original);
          for (const ref of getReferences(original, dictionary.tokens)) {
            // SD returns the referenced token's path on `.path`; for some refs it
            // arrives on `.ref`. Use whichever is present.
            const refPath = ref.path ?? ref.ref;
            value = value.replace(`{${refPath.join('.')}}`, `var(--${ref.name})`);
          }
        }
        // JSON.stringify the value so embedded quotes (e.g. the `'Geist Mono'`
        // produced by the fontFamily/css transform) and other specials are escaped.
        return `  ${JSON.stringify(token.name)}: ${JSON.stringify(String(value))},`;
      })
      .join('\n');
    return [
      '/* Generated by Style Dictionary — Canopy Roots typed token export. Do not edit. */',
      'export const tokens = {',
      entries,
      '} as const;',
      '',
      'export type Tokens = typeof tokens;',
      'export type TokenName = keyof Tokens;',
      '',
    ].join('\n');
  },
});

export default {
  source: ['tokens/**/*.json'],
  platforms: {
    css: {
      transforms: cssTransforms,
      buildPath: 'dist/',
      files: [
        {
          destination: 'tokens.css',
          format: 'css/variables',
          options: { outputReferences: true },
        },
      ],
    },
    tailwind: {
      transforms: cssTransforms,
      buildPath: 'dist/',
      files: [
        {
          destination: 'tailwind-preset.css',
          format: 'tailwind/preset-v4',
        },
      ],
    },
    ts: {
      transforms: cssTransforms,
      buildPath: 'dist/',
      files: [
        {
          destination: 'tokens.ts',
          format: 'typescript/typed-export',
        },
      ],
    },
  },
};
