import { execFileSync } from 'node:child_process';
import { existsSync, mkdtempSync, readFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { buildSwift, renderSwift } from './swift.mjs';

/**
 * The iOS/Swift export (spec 0032): a brand's DTCG files -> one `Tokens.swift` with every semantic
 * colour as a light+dark `Color`, plus Canopy's core spacing / radius / type scale as CGFloat/Font.
 * Uses the sunset brand example as the fixture.
 */
const here = dirname(fileURLToPath(import.meta.url));
const brand = (f: string) => resolve(here, 'examples/sunset', f);

let outDir: string;
let swift: string;

beforeAll(async () => {
  outDir = mkdtempSync(join(tmpdir(), 'canopy-swift-'));
  const res = await buildSwift({
    name: 'sunset',
    primitives: brand('primitive.json'),
    semantic: brand('semantic.json'),
    semanticDark: brand('semantic.dark.json'),
    outFile: join(outDir, 'Tokens.swift'),
  });
  swift = res.swift;
});

afterAll(() => rmSync(outDir, { recursive: true, force: true }));

describe('Swift emitter - generated Tokens.swift', () => {
  it('carries the do-not-edit generated header and the imports', () => {
    expect(swift).toMatch(/^\/\/ Do not edit - generated by Style Dictionary/);
    expect(swift).toContain('import SwiftUI');
    expect(swift).toContain('#if canImport(UIKit)');
  });

  it('generates the Color(light:dark:) adaptive helper', () => {
    expect(swift).toContain('init(light: UInt, dark: UInt)');
    // The dynamic UIColor provider is what makes it adapt at runtime.
    expect(swift).toContain('UIColor { traits in');
    expect(swift).toContain('traits.userInterfaceStyle == .dark');
  });

  it('emits every semantic colour under CanopyColor as a light + dark hex', () => {
    expect(swift).toContain('public enum CanopyColor {');
    // primary is the sunset anchor: ember.600 light / ember.400 dark.
    expect(swift).toContain('public static let primary = Color(light: 0x8F4D22, dark: 0xD88A57)');
    // A role must never emit a bare single hex - every CanopyColor member is light+dark.
    const colorBlock = swift.slice(
      swift.indexOf('enum CanopyColor'),
      swift.indexOf('}', swift.indexOf('enum CanopyColor')),
    );
    const memberLines = colorBlock.match(/public static let \w+ = Color\(.*\)/g) ?? [];
    expect(memberLines.length).toBeGreaterThan(30);
    for (const line of memberLines) {
      expect(line, line).toMatch(/Color\(light: 0x[0-9A-F]{6}, dark: 0x[0-9A-F]{6}\)/);
    }
  });

  it('emits the spacing scale as CGFloat points (rem * 16)', () => {
    expect(swift).toContain('public enum CanopySpacing {');
    expect(swift).toContain('public static let x4: CGFloat = 16'); // 1rem -> 16pt
    expect(swift).toContain('public static let x0_5: CGFloat = 2'); // 0.125rem -> 2pt (fractional step)
    expect(swift).toContain('public static let x0: CGFloat = 0');
  });

  it('emits the radius scale, keeping a raw px pill as-is', () => {
    expect(swift).toContain('public enum CanopyRadius {');
    expect(swift).toContain('public static let md: CGFloat = 8'); // 0.5rem -> 8pt
    expect(swift).toContain('public static let full: CGFloat = 9999'); // 9999px stays a number
  });

  it('emits type sizes + Font helpers + line-height multipliers', () => {
    expect(swift).toContain('public enum CanopyFont {');
    expect(swift).toContain('public static let sizeBase: CGFloat = 16'); // text.base 1rem -> 16pt
    expect(swift).toContain(
      'public static func sizeBaseFont() -> Font { .system(size: sizeBase) }',
    );
    expect(swift).toContain('public static let leadingTight: CGFloat = 1.2'); // unitless leading
  });

  it('writes Tokens.swift to disk and reports the roles', async () => {
    const dir = mkdtempSync(join(tmpdir(), 'canopy-swift-out-'));
    try {
      const res = await buildSwift({
        name: 'sunset',
        primitives: brand('primitive.json'),
        semantic: brand('semantic.json'),
        semanticDark: brand('semantic.dark.json'),
        outFile: join(dir, 'Tokens.swift'),
      });
      expect(existsSync(res.outFile)).toBe(true);
      expect(res.roles).toContain('color-primary');
      expect(readFileSync(res.outFile, 'utf8')).toBe(res.swift);
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });
});

describe('renderSwift - pure assembly', () => {
  it('falls back to the light hex for a role with no dark override', () => {
    const out = renderSwift(
      'demo',
      { 'color-primary': '#112233' },
      {},
      { 'space-4': { type: 'dimension', value: '1rem' } },
    );
    // No dark value supplied -> light is reused as the dark value (adapts to nothing, stays legible).
    expect(out).toContain('public static let primary = Color(light: 0x112233, dark: 0x112233)');
    expect(out).toContain('public static let x4: CGFloat = 16');
  });

  it('throws loudly on a non-hex colour value', () => {
    expect(() =>
      renderSwift('demo', { 'color-primary': 'rgb(1,2,3)' }, { 'color-primary': '#000000' }, {}),
    ).toThrow(/6-digit hex/);
  });
});

describe('Swift emitter - roots-swift CLI', () => {
  const cli = resolve(here, 'cli-swift.mjs');

  it('generates Tokens.swift from a brand config, honoring --out', () => {
    const dir = mkdtempSync(join(tmpdir(), 'canopy-swift-cli-'));
    try {
      const out = join(dir, 'Tokens.swift');
      const stdout = execFileSync('node', [cli, brand('brand.config.json'), '--out', out], {
        encoding: 'utf8',
      });
      expect(stdout).toMatch(/wrote/);
      expect(stdout).toMatch(/semantic colors/);
      expect(existsSync(out)).toBe(true);
      expect(readFileSync(out, 'utf8')).toMatch(/enum CanopyColor/);
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });

  it('exits non-zero on a missing config', () => {
    expect(() =>
      execFileSync('node', [cli, join(here, 'does-not-exist.json')], { stdio: 'pipe' }),
    ).toThrow();
  });
});
